@echo off
echo Killing node processes...
taskkill /F /IM node.exe 2>nul
echo Removing .next folder...
rd /s /q "%~dp0..\apps\web\.next" 2>nul
echo Generating Prisma client...
cd /d "%~dp0.."
call pnpm --filter @eft-tracker/web run prisma:generate
echo Starting dev server...
call npm run dev
